//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPP_GESTIONEMPLEADOS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Acceso
    {
        public int Id { get; set; }
        [DisplayName("Usuario: ")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string Login { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Campo obligatorio")]
        [DisplayName("Contraseña: ")]
        public string Pass { get; set; }
        public Nullable<System.DateTime> Fecha_Ultima_Conexion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
