//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPP_GESTIONEMPLEADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficio_Antiguedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficio_Antiguedad()
        {
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Annos_Antiguedad { get; set; }
        public Nullable<double> porcentaje_antiguedad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
