//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPP_GESTIONEMPLEADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public int id { get; set; }
        public int rut_empleado { get; set; }
        public Nullable<double> descuento_afp { get; set; }
        public Nullable<double> seguro_vida { get; set; }
        public Nullable<double> descuento_salud { get; set; }
        public Nullable<double> seguro_cesantia { get; set; }
        public Nullable<double> total_descuentos { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
