//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPP_GESTIONEMPLEADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public int rut { get; set; }
        public string dv { get; set; }
        public string nombre { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public Nullable<int> annos_experiencia { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string email { get; set; }
        public Nullable<int> telefono { get; set; }
        public string direccion { get; set; }
        public string nombre_profesion { get; set; }
        public Nullable<int> numero_cargas { get; set; }
        public Nullable<System.DateTime> fecha_contrato { get; set; }
        public Nullable<int> salud_id { get; set; }
        public Nullable<int> afp_id { get; set; }
        public Nullable<int> desc_id { get; set; }
        public Nullable<int> asignacion_id { get; set; }
        public Nullable<int> antiguedad_id { get; set; }
        public Nullable<double> sueldo_base { get; set; }
        public Nullable<double> sueldo_liquido { get; set; }
    
        public virtual Afp Afp { get; set; }
        public virtual Asignacion_familiar Asignacion_familiar { get; set; }
        public virtual Beneficio_Antiguedad Beneficio_Antiguedad { get; set; }
        public virtual Descuento Descuento { get; set; }
        public virtual Otros_Descuentos Otros_Descuentos { get; set; }
        public virtual Salud Salud { get; set; }
        public virtual Haberes Haberes { get; set; }
    }
}
