//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPP_GESTIONEMPLEADOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberes
    {
        public int id { get; set; }
        public int rut_empleado { get; set; }
        public Nullable<double> hora_extra { get; set; }
        public Nullable<double> comision { get; set; }
        public Nullable<double> bono { get; set; }
        public Nullable<double> colacion { get; set; }
        public Nullable<double> movilizacion { get; set; }
        public Nullable<double> sueldo_base { get; set; }
        public Nullable<double> monto_familiar { get; set; }
        public Nullable<double> total_haberes { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
