//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPP_GESTIONEMPLEADOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionEmpleadosDBEntities : DbContext
    {
        public GestionEmpleadosDBEntities()
            : base("name=GestionEmpleadosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acceso> Acceso { get; set; }
        public virtual DbSet<Afp> Afp { get; set; }
        public virtual DbSet<Asignacion_familiar> Asignacion_familiar { get; set; }
        public virtual DbSet<Beneficio_Antiguedad> Beneficio_Antiguedad { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Haberes> Haberes { get; set; }
        public virtual DbSet<Otros_Descuentos> Otros_Descuentos { get; set; }
        public virtual DbSet<Salud> Salud { get; set; }
    }
}
