//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedorCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        public string rut { get; set; }
        public string pnombre { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public int annos_xp { get; set; }
        public string genero { get; set; }
        public System.DateTime fec_nac { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string n_profesion { get; set; }
        public byte[] foto { get; set; }
    }
}
