//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedorCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_emp
    {
        public int ParametrosID { get; set; }
        public int EmpleadoID { get; set; }
        public double valor_hora { get; set; }
        public double valor_ex { get; set; }
        public int antiguedad { get; set; }
        public double isapre { get; set; }
        public double afp { get; set; }
        public int cargas_fam { get; set; }
        public double sueldo_bruto { get; set; }
        public double sueldo_liquido { get; set; }
        public double indemnizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
